In [1]:
%matplotlib qt5

# Important external dependencies
import numpy as np
import matplotlib.pyplot as plt
from sklearn.cluster import DBSCAN

# orix dependencies (tested with orix 0.1.1)
from orix.quaternion.orientation import Orientation, Misorientation
from orix.quaternion.rotation import Rotation
from orix.quaternion.symmetry import D6
from orix.quaternion.orientation_region import OrientationRegion
from orix.vector.neo_euler import AxAngle
from orix.vector import Vector3d
from orix import plot

In [2]:
#load angle data
angles = np.loadtxt('Data Files/EBSD Raw Data/AZ31B Ecomp 10e0 Int_3 raw1.txt', skiprows=17, usecols=(0,1,2))

In [3]:
ori = Orientation.from_euler(angles, convention="Krakow_Hielscher")
print(ori.size)

87017


In [4]:
print(ori)

Orientation (87017,) 1
[[ 0.2198  0.3357 -0.9128 -0.0762]
 [ 0.2198  0.3357 -0.9128 -0.0762]
 [ 0.2198  0.3357 -0.9128 -0.0762]
 ...
 [ 0.1209  0.0909  0.7537  0.6396]
 [ 0.1336  0.0986  0.7464  0.6445]
 [ 0.1277  0.0906  0.7537  0.6383]]


In [5]:
fundamental_region = OrientationRegion.from_symmetry(D6)

In [6]:
print(fundamental_region)

OrientationRegion (14,)
[[ 0.7071 -0.7071 -0.     -0.    ]
 [ 0.7071 -0.6124 -0.3536  0.    ]
 [ 0.7071 -0.6124  0.3536  0.    ]
 [ 0.7071 -0.3536 -0.6124 -0.    ]
 [ 0.7071 -0.3536  0.6124  0.    ]
 [ 0.7071 -0.     -0.7071 -0.    ]
 [ 0.2588 -0.     -0.     -0.9659]
 [ 0.2588  0.      0.      0.9659]
 [ 0.7071  0.      0.7071  0.    ]
 [ 0.7071  0.3536 -0.6124 -0.    ]
 [ 0.7071  0.3536  0.6124  0.    ]
 [ 0.7071  0.6124 -0.3536 -0.    ]
 [ 0.7071  0.6124  0.3536 -0.    ]
 [ 0.7071  0.7071  0.      0.    ]]


In [9]:
import orix

Help on package orix:

NAME
    orix

PACKAGE CONTENTS
    base (package)
    crystal_map (package)
    io (package)
    plot (package)
    quaternion (package)
    sampling (package)
    scalar (package)
    tests (package)
    vector (package)

DATA
    __author_email__ = 'pyxem.team@gmail.com'
    __description__ = 'orix is an open-source python library for handling ...

VERSION
    0.5.1

AUTHOR
    Ben Martineau, Phillip Crout, Håkon Wiik Ånes, Duncan Johnstone

CREDITS
    ['Ben Martineau', 'Phillip Crout', 'Håkon Wiik Ånes', 'Duncan Johnstone', 'Simon Høgås']

FILE
    c:\users\green\appdata\local\continuum\anaconda3\lib\site-packages\orix\__init__.py




In [10]:
help(orix)
dir(orix)

Help on package orix:

NAME
    orix

PACKAGE CONTENTS
    base (package)
    crystal_map (package)
    io (package)
    plot (package)
    quaternion (package)
    sampling (package)
    scalar (package)
    tests (package)
    vector (package)

DATA
    __author_email__ = 'pyxem.team@gmail.com'
    __description__ = 'orix is an open-source python library for handling ...

VERSION
    0.5.1

AUTHOR
    Ben Martineau, Phillip Crout, Håkon Wiik Ånes, Duncan Johnstone

CREDITS
    ['Ben Martineau', 'Phillip Crout', 'Håkon Wiik Ånes', 'Duncan Johnstone', 'Simon Høgås']

FILE
    c:\users\green\appdata\local\continuum\anaconda3\lib\site-packages\orix\__init__.py




['__author__',
 '__author_email__',
 '__builtins__',
 '__cached__',
 '__credits__',
 '__description__',
 '__doc__',
 '__file__',
 '__loader__',
 '__name__',
 '__package__',
 '__path__',
 '__spec__',
 '__version__',
 'base',
 'plot',
 'quaternion',
 'scalar',
 'vector']