In [30]:
import numpy
from math import sqrt

#load file, skip header, load angles and coordinates
data = numpy.loadtxt('Raw Data/AZ31B Ecomp 10e0 Int_3 raw1.txt', skiprows=17, usecols=(0,1,2,3,4))
print(data)
#random_rows = np.random.choice(data, 100, replace=False)
#print(random_rows)
data_sample=data[0:80000:100]

[[  4.7313    2.67202   0.88482   0.        0.     ]
 [  4.7313    2.67202   0.88482   0.4       0.     ]
 [  4.7313    2.67202   0.88482   0.8       0.     ]
 ...
 [  2.83479   1.72413   6.21647 108.8     109.46561]
 [  2.80588   1.70473   6.21025 109.2     109.46561]
 [  2.82442   1.72403   6.2053  109.6     109.46561]]


In [6]:
# #if angles close - five degrees & grids location close -> pixel
# #pixels -> dictionary of grains, histogram of number of particles i.e. len of key is grain size

# from collections import defaultdict

# #initialize
# grains = defaultdict(list)
# row_array=[]
# row_list=()

# #test with row 0
# row_array=data[0]
# row_list=list(row_array)
# grains[0].append(row_list)

# #cluster parameters
# distance_threshold=10
# angle_threshold=5

# #assign each particle to a grain, create a new grain if it is not part of an existing grain 
# for row in data:
#     #see if it belongs to an existing grain
#     for key in grains:
#         row_array=grains[key]
#         row_list=list(row_array[key])
#         if (0<angle_threshold) and (sqrt((row[3]-row_list[3])**2+(row[4]-row_list[4])**2)<distance_threshold):
#             row_list=list(row)
#             grains[key].append(row_list)
    
# print(len(grains[0]))

In [7]:
# from collections import defaultdict

# grains = defaultdict(list)
# row_array=[]
# row_list=()
# new_key=0
# euler_one=[0,0,0]
# euler_two=[0,0,0]

# distance_threshold=10
# angle_threshold=5

# #is the particle in the grains dictionary
# def indict(row):
#     for key in grains:
#         row_array=grains[key]
#         row_list=list(row_array) #row_list=list(row_array[key]), raise error case
#         euler_one=[row[0],row[1],row[2]]
#         print(row_list)
#         #error if there is not already a value?
#         euler_two=[row_list[0][0],row_list[0][1],row_list[0][2]]
#         if (misorientation(euler_one,euler_two)<5) and (sqrt((row[3]-row_list[0][3])**2+(row[4]-row_list[0][4])**2)<distance_threshold):
#             print('True')
#             return True
#     else:
#         print(False)
        
#         return False

# #test function
# row_array=data[0]
# row_list=list(row_array)
# grains[0].append(row_list)
# row_array=data[4]
# row_list=list(row_array)
# grains[1].append(row_list)
# #print(grains)
# # for row in data:
# #     print(indict(row))
    
# #forms grain of size 4 based on first row!

# for row in data:            
#     if indict(row) is True:
#         #look at again
#         row_list=list(row)
#         grains[key].append(row_list) 
#     else:
#         grains[new_key]=row
#         new_key+=1
        
# #error 'numpy.float64' object is not iterable

In [17]:
import math
import numpy as np

#https://en.wikipedia.org/wiki/Misorientation
euler_one=[math.radians(90),math.radians(35),math.radians(45)] #copper
euler_two=[math.radians(59),math.radians(37),math.radians(63)] #S3
#phi1, PHI, phi2

def misorientation(euler_one, euler_two):
    #orientation matrices
    g_one=np.array([[((math.cos(euler_one[0]))*(math.cos(euler_one[2]))-(math.sin(euler_one[0]))*(math.sin(euler_one[2]))*(math.cos(euler_one[1]))),((math.sin(euler_one[0]))*(math.cos(euler_one[2]))+(math.cos(euler_one[0]))*(math.sin(euler_one[2]))*(math.cos(euler_one[1]))),((math.sin(euler_one[2]))*(math.sin(euler_one[1])))],
                [(-(math.cos(euler_one[0]))*(math.sin(euler_one[2]))-(math.sin(euler_one[0]))*(math.cos(euler_one[2]))*(math.cos(euler_one[1]))),(-(math.sin(euler_one[0]))*(math.sin(euler_one[2]))+(math.cos(euler_one[0]))*(math.cos(euler_one[2]))*(math.cos(euler_one[1]))),((math.cos(euler_one[2]))*(math.sin(euler_one[1])))],
                [((math.sin(euler_one[0]))*(math.sin(euler_one[1]))),(-(math.cos(euler_one[0]))*(math.sin(euler_one[1]))),(math.cos(euler_one[1]))]        
                ])
   
    #euler_two
    g_two=np.array([[((math.cos(euler_two[0]))*(math.cos(euler_two[2]))-(math.sin(euler_two[0]))*(math.sin(euler_two[2]))*(math.cos(euler_two[1]))),((math.sin(euler_two[0]))*(math.cos(euler_two[2]))+(math.cos(euler_two[0]))*(math.sin(euler_two[2]))*(math.cos(euler_two[1]))),((math.sin(euler_two[2]))*(math.sin(euler_two[1])))],
                [(-(math.cos(euler_two[0]))*(math.sin(euler_two[2]))-(math.sin(euler_two[0]))*(math.cos(euler_two[2]))*(math.cos(euler_two[1]))),(-(math.sin(euler_two[0]))*(math.sin(euler_two[2]))+(math.cos(euler_two[0]))*(math.cos(euler_two[2]))*(math.cos(euler_two[1]))),((math.cos(euler_two[2]))*(math.sin(euler_two[1])))],
                [((math.sin(euler_two[0]))*(math.sin(euler_two[1]))),(-(math.cos(euler_two[0]))*(math.sin(euler_two[1]))),(math.cos(euler_two[1]))]        
                ])
    
    #misorientation matrix
    delta_g=np.dot(g_one,np.linalg.inv(g_two))
                     
    
    #misorientation angle
    #error handling for rounding errors outside of domain
    try:
        theta=math.acos((delta_g[0,0]+delta_g[1,1]+delta_g[2,2]-1)/2)
    except:
        if (((delta_g[0,0]+delta_g[1,1]+delta_g[2,2]-1)/2)>1):
            theta=0
        else:
            theta=180

    return math.degrees(theta)

print(misorientation(euler_one,euler_two))

19.576491272305066


In [9]:
# from collections import defaultdict

# grains = defaultdict(list)
# row_array=[]
# row_list=()
# new_key=1
# euler_one=[0,0,0]
# euler_two=[0,0,0]
# # 
# distance_threshold=10
# angle_threshold=5

# #add keys to prevent none return
# #while x < 5000:
    
# #or randomly initialize?

# #is the pixel in the grains dictionary
# def indict(row):
#     for key in grains:
#         print(key)
#         try:
#             print('try')
#             row_array=grains[key]
#             row_list=list(row_array) 
#             euler_one=[row[0],row[1],row[2]]
#             #raises error if value for key does not exist, how to handle? 
#             euler_two=[row_list[0][0],row_list[0][1],row_list[0][2]]
#             if (misorientation(euler_one,euler_two)<5) and (sqrt((row[3]-row_list[0][3])**2+(row[4]-row_list[0][4])**2)<distance_threshold):
#                 print('True')
#                 return True, key
#         except:
#             #
#             print('False')
#             return False, key       
#         else:
#             #not in the key
#             print('break')
#             return False, key 
#             break
              
# #dictionary starting value
# row_array=data[0]
# row_list=list(row_array)
# grains[0].append(row_list)
 
    
# #use zip?
# for row in data: 
#     print(row)
#     Non=0
#     try:
#         truu, keey = indict(row)
#     except:
#         Non==True
#     print(truu)
#     print(keey)
#     if truu is True:
#         #look at again
#         row_list=list(row)
#         grains[keey].append(row_list) 
#         print('new pixel')
#         print(grains)
#     if truu is False or Non is True:
#         #if it returns False or None
#         grains[new_key]=row
#         new_key+=1
#         print('new grain')
#         print(grains)
        

In [10]:
# from collections import defaultdict

# grains = defaultdict(list)
# row_array=[]
# row_list=()
# new_key=1
# euler_one=[0,0,0]
# euler_two=[0,0,0]

# distance_threshold=10
# angle_threshold=5

# #is the pixel in the grains dictionary
# def indict(row):
#     new_key=0
#     for key in grains:
#         #print('key '+ str(key))
#         try:
#             row_array=grains[key]
#             row_list=list(row_array) #row_list=list(row_array[key]), raise error case
#             euler_one=[row[0],row[1],row[2]]
#             #print(row_list)
#             #error if there is not already a value?
#             euler_two=[row_list[0][0],row_list[0][1],row_list[0][2]]
#             if (misorientation(euler_one,euler_two)<5) and (sqrt((row[3]-row_list[0][3])**2+(row[4]-row_list[0][4])**2)<distance_threshold):
#                 print('True')
#                 return True,key
#         except:
#             print('continue')
#             new_key+=1
#             continue
                
#     print('Not in grains')
#     return False, new_key

# #dictionary starting value
# # row_array=data[0]
# # row_list=list(row_array)
# # grains[0].append(row_list)
    
# #forms grain of size 4 based on first row!

# for row in data: 
#     truu, keey = indict(row)
#     if truu is True:
#         #look at again
#         row_list=list(row)
#         grains[keey].append(row_list) 
#         print(grains)
#     else:
#         grains[new_key]=row
#         print(grains)
        

In [11]:
# from collections import defaultdict

# grains = defaultdict(list)
# row_array=[]
# row_list=()
# new_key=1
# euler_one=[0,0,0]
# euler_two=[0,0,0]

# distance_threshold=10
# angle_threshold=5

# #add keys to prevent none return
# #while x < 5000:
    
# #or randomly initialize?

# #is the pixel in the grains dictionary
# def indict(row):
#     for key in grains:
#         print(key)
#         row_array=grains[key]
#         row_list=list(row_array) 
#         euler_one=[row[0],row[1],row[2]]
#         #raises error if value for key does not exist, how to handle? 
#         euler_two=[row_list[0][0],row_list[0][1],row_list[0][2]]
#         if (misorientation(euler_one,euler_two)<5) and (sqrt((row[3]-row_list[0][3])**2+(row[4]-row_list[0][4])**2)<distance_threshold):
#             print('True')
#             return True, key
#         else:
#             print('continue')
#             continue
#     return False,key
              
# #dictionary starting value
# row_array=data[0]
# row_list=list(row_array)
# grains[0].append(row_list)
 
    
# #use zip?
# for row in data: 
#     print(row)
#     truu, keey = indict(row)
#     if truu is True:
#         row_list=list(row)
#         grains[keey].append(row_list) 
#         print('new pixel')
#         print(grains)
#     if truu is False:
#         print(row_list)
#         grains[keey+1].append(row_list)
#         print('new grain')
#         print(grains)
        

In [33]:
from collections import defaultdict

grains = defaultdict(list)
row_array=[]
row_list=()
new_key=1
euler_one=[0,0,0]
euler_two=[0,0,0]

distance_threshold=10
angle_threshold=5

#add keys to prevent none return
#while x < 5000:
    
#or randomly initialize?

#is the pixel in the grains dictionary
def indict(row):
    for key in grains:
        #print(key)
        row_array=grains[key]
        row_list=list(row_array) 
        euler_one=[row[0],row[1],row[2]]
        #raises error if value for key does not exist, how to handle? 
        euler_two=[row_list[0][0],row_list[0][1],row_list[0][2]]
        if (misorientation(euler_one,euler_two)<5) and (sqrt((row[3]-row_list[0][3])**2+(row[4]-row_list[0][4])**2)<distance_threshold):
            #print('True')
            return True, key
        else:
            #print('continue')
            continue
    return False,key
              
#dictionary starting value
row_array=data[0]
row_list=list(row_array)
grains[0].append(row_list)
 
    
#use zip?
for row in data_sample: 
    #print(row)
    truu, keey = indict(row)
    if truu is True:
        row_list=list(row)
        grains[keey].append(row_list) 
#         print('new pixel')
#         print(grains)
    if truu is False:
        row_list=list(row)
        grains[keey+1].append(row_list)
#         print('new grain')
#         print(grains)

#doesn't know when to stop
    
print(len(grains))

645


In [32]:
for x in range(20):
    distance_threshold=x
    print(len(grains))
    

645
645
645
645
645
645
645
645
645
645
645
645
645
645
645
645
645
645
645
645


In [37]:
# from collections import defaultdict

# grains = defaultdict(list)
# row_array=[]
# row_list=()
# new_key=1
# euler_one=[0,0,0]
# euler_two=[0,0,0]

# distance_threshold=10
# angle_threshold=5

# #add keys to prevent none return
# #while x < 5000:
    
# #or randomly initialize?

# #is the pixel in the grains dictionary
# def indict(row):
#     for key in grains:
#         #print(key)
#         row_array=grains[key]
#         row_list=list(row_array) 
#         euler_one=[row[0],row[1],row[2]]
#         #raises error if value for key does not exist, how to handle? 
#         euler_two=[row_list[0][0],row_list[0][1],row_list[0][2]]
#         if (misorientation(euler_one,euler_two)<5) and (sqrt((row[3]-row_list[0][3])**2+(row[4]-row_list[0][4])**2)<distance_threshold):
#             #print('True')
#             return True, key
#         else:
#             #print('continue')
#             continue
# #     return False,key
              
# #dictionary starting value
# row_array=data[0]
# row_list=list(row_array)
# grains[0].append(row_list)
 
    
# #use zip?
# def grain_dict(x):
#     row_array=x[0]
#     row_list=list(row_array)
#     grains[0].append(row_list)
#     for row in x: 
#         truu, keey = indict(row)
#         if truu is True:
#             row_list=list(row)
#             grains[keey].append(row_list) 
#         if truu is False:
#             row_list=list(row)
#             grains[keey+1].append(row_list)

# print(len(grain_dict(data_sample)))

TypeError: object of type 'NoneType' has no len()