In [12]:
import numpy
from math import sqrt

#load file, skip header, load angles and coordinates
data = numpy.loadtxt('Raw Data/AZ31B Ecomp 10e0 Int_3 raw1.txt', skiprows=17, usecols=(0,1,2,3,4))
print(data)

[[  4.7313    2.67202   0.88482   0.        0.     ]
 [  4.7313    2.67202   0.88482   0.4       0.     ]
 [  4.7313    2.67202   0.88482   0.8       0.     ]
 ...
 [  2.83479   1.72413   6.21647 108.8     109.46561]
 [  2.80588   1.70473   6.21025 109.2     109.46561]
 [  2.82442   1.72403   6.2053  109.6     109.46561]]


In [6]:
#if angles close - five degrees & grids location close -> particle
#particles -> dictionary of grains, histogram of number of particles i.e. len of key is grain size
#pixels

from collections import defaultdict

#initialize
grains = defaultdict(list)
row_array=[]
row_list=()

#test with row 0
row_array=data[0]
row_list=list(row_array)
grains[0].append(row_list)

#cluster parameters
distance_threshold=10
angle_threshold=5

#assign each particle to a grain, create a new grain if it is not part of an existing grain 
for row in data:
    #see if it belongs to an existing grain
    for key in grains:
        row_array=grains[key]
        row_list=list(row_array[key])
        if (0<angle_threshold) and (sqrt((row[3]-row_list[3])**2+(row[4]-row_list[4])**2)<distance_threshold):
            row_list=list(row)
            grains[key].append(row_list)
    
print(len(grains[0]))

586


In [2]:
from collections import defaultdict

grains = defaultdict(list)
row_array=[]
row_list=()
new_key=0
euler_one=[0,0,0]
euler_two=[0,0,0]

distance_threshold=10
angle_threshold=5

#is the particle in the grains dictionary
def indict(row):
    #print(row)
    for key in grains:
        row_array=grains[key]
        row_list=list(row_array[key])
        euler_one=[row[0],row[1],row[2]]
        euler_two=[row_list[0],row_list[1],row_list[2]]
        if (misorientation(euler_one,euler_two)<5) and (sqrt((row[3]-row_list[3])**2+(row[4]-row_list[4])**2)<distance_threshold):
            return True
    else:
        return False

#test function
row_array=data[0]
row_list=list(row_array)
grains[0].append(row_list)
print(grains)
for row in data:
    print(indict(row))
    
#forms grain of size 4 based on first row!

for row in data:            
    if indict(row) is True:
        #look at again
        row_list=list(row)
        grains[key].append(row_list) 
    else:
        grains[new_key]=row
        new_key+=1
        
#error 'numpy.float64' object is not iterable

NameError: name 'data' is not defined

In [77]:
import math
import numpy as np

#https://en.wikipedia.org/wiki/Misorientation
euler_one=[math.radians(90),math.radians(35),math.radians(45)] #copper
euler_two=[math.radians(59),math.radians(37),math.radians(63)] #S3
#phi1, PHI, phi2

def misorientation(euler_one, euler_two):
    #orientation matrices
    g_one=np.array([[((math.cos(euler_one[0]))*(math.cos(euler_one[2]))-(math.sin(euler_one[0]))*(math.sin(euler_one[2]))*(math.cos(euler_one[1]))),((math.sin(euler_one[0]))*(math.cos(euler_one[2]))+(math.cos(euler_one[0]))*(math.sin(euler_one[2]))*(math.cos(euler_one[1]))),((math.sin(euler_one[2]))*(math.sin(euler_one[1])))],
                [(-(math.cos(euler_one[0]))*(math.sin(euler_one[2]))-(math.sin(euler_one[0]))*(math.cos(euler_one[2]))*(math.cos(euler_one[1]))),(-(math.sin(euler_one[0]))*(math.sin(euler_one[2]))+(math.cos(euler_one[0]))*(math.cos(euler_one[2]))*(math.cos(euler_one[1]))),((math.cos(euler_one[2]))*(math.sin(euler_one[1])))],
                [((math.sin(euler_one[0]))*(math.sin(euler_one[1]))),(-(math.cos(euler_one[0]))*(math.sin(euler_one[1]))),(math.cos(euler_one[1]))]        
                ])
   
    #euler_two
     g_two=np.array([[((math.cos(euler_two[0]))*(math.cos(euler_two[2]))-(math.sin(euler_two[0]))*(math.sin(euler_two[2]))*(math.cos(euler_two[1]))),((math.sin(euler_two[0]))*(math.cos(euler_two[2]))+(math.cos(euler_two[0]))*(math.sin(euler_two[2]))*(math.cos(euler_two[1]))),((math.sin(euler_two[2]))*(math.sin(euler_two[1])))],
                [(-(math.cos(euler_two[0]))*(math.sin(euler_two[2]))-(math.sin(euler_two[0]))*(math.cos(euler_two[2]))*(math.cos(euler_two[1]))),(-(math.sin(euler_two[0]))*(math.sin(euler_two[2]))+(math.cos(euler_two[0]))*(math.cos(euler_two[2]))*(math.cos(euler_two[1]))),((math.cos(euler_two[2]))*(math.sin(euler_two[1])))],
                [((math.sin(euler_two[0]))*(math.sin(euler_two[1]))),(-(math.cos(euler_two[0]))*(math.sin(euler_two[1]))),(math.cos(euler_two[1]))]        
                ])
    
    #misorientation matrix
    delta_g=np.dot(g_one,np.linalg.inv(g_two))
                     
    
    #misorientation angle
    return math.degrees(math.acos((delta_g[0,0]+delta_g[1,1]+delta_g[2,2]-1)/2))

print(misorientation(euler_one,euler_two))

19.576491272305066
